apiVersion: autoscaling/v2beta2
kind: HorizontalPodAUtoscaler
metadata:
  name: hpa-name
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-name # nama deploymentnya kemana
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70 # rata2 pengunaan CPU 70% akan trigger HPA
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 # rata2 penggunaan memory 70% akan trigger HPA (hati2)
