apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
  labels: 
    label-key1: label-value1
  annotations:
    description: contoh replication controller
spec:
  replicas: 3
  selector:
    app: webserver
  template:
    metadata:
      name: nginx
      labels: 
        app: webserver
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80